/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$(document).ready(function() {
	
	$("#Home").click(function(e) {
		$("#HomeDiv").show();
		$("#AllUserDiv").hide();
		$("#SearchUserDiv").hide();
		$("#InsertUserDiv").hide();
		$("#VehicleInfoDiv").hide();
		$("#LoginDiv").hide();
		$("#InsertVehicleDiv").hide();
		$("#AllVehicleDiv").hide();
		$("#AboutDiv").hide();
		$("#RegisterDiv").hide();
		$("#AllRentalsDiv").hide();
		$("#InsertRentalDiv").hide();
	});
	
	$("#RentNowBt").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt2").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt3").click(function(e) {

		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt4").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt5").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt6").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt7").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});
	
	$("#RentNowBt8").click(function(e) {
		if(globalUser){
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").hide();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").show();
			$("#BookDiv").hide();
		}else{
			$("#HomeDiv").hide();
			$("#AllUserDiv").hide();
			$("#SearchUserDiv").hide();
			$("#InsertUserDiv").hide();
			$("#VehicleInfoDiv").hide();
			$("#LoginDiv").show();
			$("#InsertVehicleDiv").hide();
			$("#AllVehicleDiv").hide();
			$("#AboutDiv").hide();
			$("#RegisterDiv").hide();
			$("#AllRentalsDiv").hide();
			$("#InsertRentalDiv").hide();
			$("#BookDiv").hide();
		}
	});

});
